//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkDACE.ServiceParkingSpots {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParkinSpot", Namespace="http://schemas.datacontract.org/2004/07/BOT_SpotSensors")]
    [System.SerializableAttribute()]
    public partial class ParkinSpot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BatteryStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BatteryStatus {
            get {
                return this.BatteryStatusField;
            }
            set {
                if ((this.BatteryStatusField.Equals(value) != true)) {
                    this.BatteryStatusField = value;
                    this.RaisePropertyChanged("BatteryStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceParkingSpots.SpotSensors")]
    public interface SpotSensors {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SpotSensors/GetSensorDataString", ReplyAction="http://tempuri.org/SpotSensors/GetSensorDataStringResponse")]
        string GetSensorDataString(string spotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SpotSensors/GetSensorDataString", ReplyAction="http://tempuri.org/SpotSensors/GetSensorDataStringResponse")]
        System.Threading.Tasks.Task<string> GetSensorDataStringAsync(string spotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SpotSensors/GetSensorDataUsingDataContract", ReplyAction="http://tempuri.org/SpotSensors/GetSensorDataUsingDataContractResponse")]
        ParkDACE.ServiceParkingSpots.ParkinSpot GetSensorDataUsingDataContract(string spotId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SpotSensors/GetSensorDataUsingDataContract", ReplyAction="http://tempuri.org/SpotSensors/GetSensorDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ParkDACE.ServiceParkingSpots.ParkinSpot> GetSensorDataUsingDataContractAsync(string spotId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SpotSensorsChannel : ParkDACE.ServiceParkingSpots.SpotSensors, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpotSensorsClient : System.ServiceModel.ClientBase<ParkDACE.ServiceParkingSpots.SpotSensors>, ParkDACE.ServiceParkingSpots.SpotSensors {
        
        public SpotSensorsClient() {
        }
        
        public SpotSensorsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpotSensorsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpotSensorsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpotSensorsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSensorDataString(string spotId) {
            return base.Channel.GetSensorDataString(spotId);
        }
        
        public System.Threading.Tasks.Task<string> GetSensorDataStringAsync(string spotId) {
            return base.Channel.GetSensorDataStringAsync(spotId);
        }
        
        public ParkDACE.ServiceParkingSpots.ParkinSpot GetSensorDataUsingDataContract(string spotId) {
            return base.Channel.GetSensorDataUsingDataContract(spotId);
        }
        
        public System.Threading.Tasks.Task<ParkDACE.ServiceParkingSpots.ParkinSpot> GetSensorDataUsingDataContractAsync(string spotId) {
            return base.Channel.GetSensorDataUsingDataContractAsync(spotId);
        }
    }
}
